### ISSUE TITLE
Command 'date' throw warning in ubuntu bash 

### ISSUE THREAD

**Issue by lappodeveloper** [braun-daniel/azure-pim-on-shell#5]
Hey Daniel,
I execute the pim script in ubuntu bash and it works perfectly.
There is just this annoying warning when it executes the 'date' command: 

```
lappo#:~$ pim
Please provide a justification message: costs overview 
date: invalid option -- 'v'
Try 'date --help' for more information.
PIM assignment active. Expires: 
lappo#:~$
```

I have implemented the fix locally, but I could push it in github if you like.

**Comment by braun-daniel** [comment]
Hi @lappodeveloper 

Thanks for catching that and already implementing a fix—much appreciated! 🎉 Feel free to push it, and I’ll review it ASAP.

Cheers,
Daniel
